image: docker:git
services:
- docker:dind

stages:
  - build

docker_build:
  stage: build
  script:
    - gitpath=`cat .gitpath`
    - docker login --username="$USERNAME" --password="$PASSWORD" registry.gitlab.com
    - docker build -t registry.gitlab.com/$gitpath .
    - docker push registry.gitlab.com/$gitpath

